### ISSUE TITLE
Wrong encoding for cyrillic docstrings

### ISSUE THREAD

**Issue by vasa-chi** [sadovnychyi/autocomplete-python#210]
When autocompletion provides a function with cyrillic docstrings, it outputs gibberish :)

<img width="685" alt="2016-06-02 12 39 34" src="https://cloud.githubusercontent.com/assets/180167/15740790/3fd1b866-28bf-11e6-86b7-9c2699409ff1.png">

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/15744834/f57acbb2-2900-11e6-8a9b-33d7722210fc.png)

Works for me on osx with default Atom's encoding. Should I try to save file in different encoding?

**Comment by sadovnychyi** [comment]
When I create a file in win-1251 encoding using sublime and then trying to open it in Atom it cannot recognize cyrillic characters at all.

**Comment by vasa-chi** [comment]
Hmm. My files are all utf-8. But I don't use `# -*- coding: utf-8 -*- #`, since it isn't required for py3 projects...

With `coding` everything is fine.

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/15745061/6e864396-2902-11e6-9b4d-5319dc0b5f8f.png)

Works even without `coding` for me. Using py3 as I remember.

**Comment by vasa-chi** [comment]
Yep. Try autocompletion from another file.

**Comment by sadovnychyi** [comment]
Ok. I can see it. Maybe it's more related to Jedi, not sure. Will check their issue tracker.

**Comment by vasa-chi** [comment]
Thank you :)

**Comment by sadovnychyi** [comment]
https://github.com/davidhalter/jedi-vim/issues/566

And looks like there's a fix:

https://github.com/davidhalter/jedi/pull/726

I could update integrated jedi to include this PR until it's merged.

Just need to make sure that it works.

**Comment by vasa-chi** [comment]
Applied davidhalter/jedi#726 manually - didn't work for me.

**Comment by sadovnychyi** [comment]
Yeah, it uses `iso-8859-1` as a default one unless that creepy bytemark (`\xef\xbb\xbf`) presented in the beginning of the source file. But it's probably presented only with special UTF-8 with BOM encoding, which is not even supported in Atom (https://github.com/atom/encoding-selector/issues/18).

Maybe the best solution here is to try to read current file encoding set in Atom and pass it to Jedi.

**Comment by sadovnychyi** [comment]
You can temporarily fix it by enforcing utf-8 encoding at this line:

https://github.com/davidhalter/jedi/blob/master/jedi/evaluate/imports.py#L445

```python
p = fast.FastParser(evaluator.grammar, common.source_to_unicode(source, 'utf-8'), p)
```

There's no way to set this using Jedi API, and I believe that it should be changed. You can upvote this issue if you think that it's valid:  https://github.com/davidhalter/jedi/issues/728

**Comment by sadovnychyi** [comment]
Fixed in 1.7.4.

**Comment by vasa-chi** [comment]
Um. Sorry, but still seeing this.
Applying your patch on `imports.py` fixes the problem for me.

**Comment by sadovnychyi** [comment]
Strange. `utf-8` should be forced everywhere already. Can you give me a case I can reproduce? I doubt that it fails in the same case like I mentioned.

**Comment by vasa-chi** [comment]
Hmm. It seems that the error is reproducable on my old projects... Anything new works fine.
Is there some sort of cache I can clean, maybe?

**Comment by sadovnychyi** [comment]
Yeah. Try to remove it.

> On Linux, this defaults to ~/.cache/jedi/, on OS X to ~/Library/Caches/Jedi/ and on Windows to %APPDATA%\Jedi\Jedi\. On Linux, if environment variable $XDG_CACHE_HOME is set, $XDG_CACHE_HOME/jedi is used instead of the default one.

**Comment by vasa-chi** [comment]
That solved it! Thanks 👍
