### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by rcatlin** [sadovnychyi/autocomplete-python#92]
**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.8.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/ryan.catlin/.atom/packages/autocomplete-python/lib/provider.coffee:113

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
  at [object Object].module.exports._deserialize (/Users/ryan.catlin/.atom/packages/autocomplete-python/lib/provider.coffee:113:30)
  at Interface.<anonymous> (/Users/ryan.catlin/.atom/packages/autocomplete-python/lib/provider.coffee:79:41)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:169:7)
  at Interface._onLine (readline.js:209:10)
  at Interface.<anonymous> (readline.js:339:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:338:11)
  at Socket.ondata (readline.js:85:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```

### Commands

```
     -3:17.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:17.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:17.4.0 editor:indent (atom-text-editor.editor.is-focused)
  6x -3:16.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:11.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:02.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:02.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -3:02.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:01.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:58 core:move-right (atom-text-editor.editor.is-focused)
  4x -2:57.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:45.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:43.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:39.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:39.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:36 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "autocomplete-python": {
    "addBracketAfterFunction": true,
    "addDotAfterModule": true,
    "useSnippets": "all"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.8.2
linter-python-pep8, v0.2.0
python-tools, v0.6.5

# Dev
No dev packages
```

**Comment by ethe** [comment]
Have the same problems.

**Comment by sadovnychyi** [comment]
Should be fixed with latest release.

**Comment by rcatlin** [comment]
@sadovnychyi, thank you!

**Comment by cbscribe** [comment]
Still seeing this error running 0.9.2.  Works for a brief time, but then the error pops up.  

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.9.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/chris/.atom/packages/autocomplete-python/lib/provider.coffee:107

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
  at [object Object].module.exports._deserialize (/Users/chris/.atom/packages/autocomplete-python/lib/provider.coffee:107:12)
  at Interface.<anonymous> (/Users/chris/.atom/packages/autocomplete-python/lib/provider.coffee:73:20)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:169:7)
  at Interface._onLine (readline.js:209:10)
  at Interface.<anonymous> (readline.js:339:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:338:11)
  at Socket.ondata (readline.js:85:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```


### Config

```json
{
  "autocomplete-python": {
    "useSnippets": "all",
    "pythonPath": "/usr/local/Cellar/python3/3.5.0/bin"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.11.0
atom-runner, v2.4.6
autocomplete-python, v0.9.2
base-16-ocean-dark-ui-theme, v1.5.1
base16-ocean-dark-syntax-theme, v0.1.5
color-picker, v2.0.13
linter, v1.9.1
linter-flake8, v1.9.1
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
This line numbers `at [object Object].module.exports._deserialize (/Users/chris/.atom/packages/autocomplete-python/lib/provider.coffee:107:12)` does not matches with 0.9.2. I think you have to restart your editor to properly update this package.

**Comment by cbscribe** [comment]
Thanks.  I had uninstalled the package and reinstalled it, but I guess that wasn't the same as a restart.  Sorry for the repost.
